### ISSUE TITLE
Wrong default value for allow query under basic configuration for InternalDNS

### ISSUE THREAD

**Issue by slobodanz** [atomia/puppetmaster-gui#79] opened 2016-09-20 11:57 UTC
Under Basic configuration for InternalDNS, default value for allow_query filed is **any** .

Because of that bind will fail to start:  intdns-rslvr named[12085]: /etc/bind/named.conf.options:2: missing ';' before '}'

Default value for  allow_query filed should be **any;**

**Comment by stefanmortensen** [comment] 2016-09-22 06:08
This is a duplicate of https://github.com/atomia/puppet-atomia/issues/166

**Closed by stefanmortensen** 2016-09-22 06:08 UTC
