### ISSUE TITLE
$ipaddress in Awstats Advanced server configuration

### ISSUE THREAD

**Issue by slobodanz** [atomia/puppetmaster-gui#80] opened 2016-09-22 09:17 UTC
When checking the advanced configuration for the Awstats server, the server_ip field had value: $ipaddress.

**Comment by stefanmortensen** [comment] 2016-09-22 13:19
Duplicate of https://github.com/atomia/puppetmaster-gui/issues/59 in general this happens when the dns is not resolvable so please check that first.

**Closed by stefanmortensen** 2016-09-22 13:19 UTC
